### ISSUE TITLE
Stacking calls does not cancel properly and animates faster than expected

### ISSUE THREAD

**Issue by sowhatdoido** [KoryNunn/scroll-into-view#84]
Exmaple: https://codesandbox.io/s/cocky-fire-qy24u

In this example, if a user clicks "Scroll Bottom", then clicks "Scroll Top" before the animation finishes, the `time` variable is not respected and the user is scrolled to the top of the page in a split second.

Should the library either handle cancelling the existing call implicitly, or at least return a method that allows us to cancel the previous animation and trigger a new one?

**Comment by KoryNunn** [comment]
I've seen this before and I have an idea how to resolve it. I'll get on it in the near future.

**Comment by KoryNunn** [comment]
Fixed and published as 1.14.2

**Comment by tommedema** [comment]
I'm still experiencing this when the element I just started scrolling to is removed from the DOM. It results in the browser scrolling to the top of the page.

Demo:
1. go to https://app.usebubbles.com/0a78304f-8c8c-489d-b3cd-03aabe7a6571
2. scroll to bottom
3. press to insert a bubble, then quickly press outside again to remove the empty bubble
4. notice the page scrolling to the top
